refresh from private repo

diff --git a/nas/setup-docker b/nas/setup-docker
--- a/nas/setup-docker
+++ b/nas/setup-docker
@@ -1,11 +1,123 @@
-# Disable k3/enable d-c
-chmod -x /usr/local/bin/k3s
-chmod -x /usr/local/bin/kube-control
-chmod +x /usr/bin/docker-compose
-chmod +x /bin/docker-compose
-systemctl disable k3s
-systemctl stop k3s
+#!/bin/bash
+# Enable TrueNAS Scale developer mode (dragonfish)
+/usr/local/libexec/disable-rootfs-protection
 
-# Replace docker config 
-cp /path/to/repo/nas/daemon.json /etc/docker/daemon.json
-systemctl restart docker
+# Disable k3
+disable_k3() {
+    echo "Disabling execution of k3 commands"
+    chmod -x /usr/local/bin/k3s
+    chmod -x /usr/local/bin/k3s-kill.sh
+    chmod -x /usr/local/bin/kube-router
+    
+    echo "Disable and stop k3 service"
+    systemctl disable k3s
+    systemctl stop k3s
+}
+
+# Misc Pre-docker setup tasks
+config_sys() {
+    # Move netdata uid, conflicts with docker uid 999
+    echo "Move netdata to different uid" 
+    [ "$(id -u netdata 2>/dev/null)" -eq 999 ] && sudo usermod -u 9999 netdata
+
+   # Bump up max watches (streams can fail when exhausted)
+   if ! grep -q "^fs.inotify.max_user_watches = 499401" /etc/sysctl.conf; then
+    echo "fs.inotify.max_user_watches = 499401" | sudo tee -a /etc/sysctl.conf > /dev/null
+    sysctl -p
+   fi
+
+}
+
+# Install docker. Steps from https://docs.docker.com/engine/install/debian/
+install_docker() {
+    echo "Re-enable apt/dpkg"
+    chmod +x /usr/bin/apt*
+    chmod +x /usr/bin/dpkg
+
+    # Add Docker's official GPG key:
+    echo "Add Docker GPG key"
+    apt-get update
+    apt-get install -y ca-certificates curl gnupg
+    install -m 0755 -d /etc/apt/keyrings
+    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
+    chmod a+r /etc/apt/keyrings/docker.gpg
+
+    # Add the repository to Apt sources:
+    echo "Add Docker repo to sources"
+    echo \
+      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
+      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
+      tee /etc/apt/sources.list.d/docker.list > /dev/null
+    apt-get update
+
+    echo "Install packages"
+    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+}
+
+# Set docker config 
+config_docker() {
+    echo "Copy daemon config"
+    cp /mnt/app/home/jon/compose/nas/daemon.json /etc/docker/daemon.json
+    touch /etc/docker.env
+    echo "Enable and start docker daemon"
+    systemctl enable docker
+    systemctl start docker
+    systemctl status docker.service
+}
+
+# "Up" the relevant compose projects to restore/start containers
+compose_up() {
+    /mnt/app/home/jon/compose/scripts/up
+    sleep 2
+    /mnt/app/home/jon/compose/scripts/up
+    sleep 2
+    /mnt/app/home/jon/compose/scripts/up
+}
+
+# Other non-standard system configuration needs 
+config_other() {
+    # Install full vim, archive utils
+    update-alternatives --remove-all vim.tiny
+    apt-get install -y vim par2 unrar p7zip-full
+    update-alternatives --install /usr/bin/vim vim /usr/bin/vim.basic 0
+    dpkg --configure -a
+    
+    # Setup zabbix user/group and rights
+    adduser --system --uid 1997 zabbix
+    addgroup --system --gid 1995 zabbix
+    usermod --gid 1995 zabbix
+    zbxsudo="zabbix ALL=(ALL) NOPASSWD: /usr/local/sbin/smartctl"
+    if ! grep -qF -- "$zbxsudo" /etc/sudoers; then
+      echo "$zbxsudo" | sudo tee -a /etc/sudoers > /dev/null
+    fi
+    ln -s /sbin/smartctl /usr/local/bin/smartctl
+}
+
+# Parameters: setup-docker [ -d | -i | -c | -s | -o | -a]
+# d: disable k3
+# m: misc pre-docker config tasks
+# i: install docker
+# c: configure docker
+# s: start containers
+# o: other post-docker config tasks
+# a: all of the above
+if [ -z "$*" ]; then echo -e "Parameters: setup-docker [ -d | -m |  -i | -c | -s | -o | -a]\n d: disable k3\n m: misc pre-docker config tasks\n i: install docker\n c: configure docker\n s: start containers\n o: other system config\n a: all of the above"; fi
+while getopts dmicosa flag 
+do
+    case $flag in 
+    d)    disable_k3;; 
+    m)    config_sys;;
+    i)    install_docker;; 
+    c)    config_docker;;
+    o)    config_other;;
+    s)    compose_up;;
+    a)    disable_k3
+          config_sys
+          install_docker
+          config_docker
+          compose_up
+          config_other;;
+    esac
+done
+exit 0;
+
diff --git a/scripts/dr b/scripts/dr
--- a/scripts/dr
+++ b/scripts/dr
@@ -1,1 +1,81 @@
-docker restart $@
+#!/bin/bash
+
+# Define container lists
+GT_CONTAINERS="gluetun prowlarr jackett autobrr lounge"
+NZBS_CONTAINERS="gluetun-nzb gluetun-nzb2 sabnzbd sabnzbd2"
+QBT_CONTAINERS="gluetun-qbt qbittorrent"
+
+# Function to show usage
+show_usage() {
+    echo "Usage: $0 [OPTIONS] [CONTAINER_NAME]"
+    echo "Restart Docker containers."
+    echo
+    echo "Options:"
+    echo "  -g              Restart base gluetun containers"
+    echo "  -n              Restart sabnzbd containers"
+    echo "  -q              Restart qbittorent containers"
+    echo "  -h              Show this help message"
+    echo
+    echo "If a CONTAINER_NAME is provided, it will restart that specific container."
+    echo "If no options or container name are provided, the script will prompt for the name of the container to restart."
+}
+
+# Function to restart containers
+restart_containers() {
+    local containers=$1
+    for container in $containers; do
+        echo "Restarting container: $container"
+        docker restart $container
+    done
+}
+
+# Check if no parameters are provided
+if [ "$#" -eq 0 ]; then
+    echo "No parameters provided."
+    show_usage
+    read -p "Enter the name of the container to restart: " container_name
+    if [ -n "$container_name" ]; then
+        echo "Restarting container: $container_name"
+        docker restart $container_name
+    else
+        echo "No container name provided. Exiting."
+        exit 1
+    fi
+    exit 0
+fi
+
+# Parse options
+while getopts ":gnqh" opt; do
+    case $opt in
+        g)
+            restart_containers "$GT_CONTAINERS"
+            exit 0
+            ;;
+
+        n)
+            restart_containers "$NZBS_CONTAINERS"
+            exit 0
+            ;;
+        q)
+            restart_containers "$QBT_CONTAINERS"
+            exit 0
+            ;;
+        h)
+            show_usage
+            exit 0
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            show_usage
+            exit 1
+            ;;
+    esac
+done
+
+# If parameters are provided but not options, assume it's a container name
+if [ -n "$1" ]; then
+    container_name=$1
+    echo "Restarting container: $container_name"
+    docker restart $container_name
+    exit 0
+fi
